apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-feed
  name: udagram-feed
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-feed
  template:
    metadata:
      labels:
        service: udagram-feed
    spec:
      containers:
      - image:  langerca/udagram-feed:latest
        name: udagram-feed
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        env:
          - name: URL
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: JWT_SECRET
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: POSTGRES_DB
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: POSTGRES_HOST
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: POSTGRES_USERNAME
      restartPolicy: Always
